### ISSUE TITLE
Solid blocks appear way too dark

### ISSUE THREAD

**Issue by alexanderneuschl** [miclav/mapcrafter#28]
Hey there! @miclav, you're the GOAT for keeping this project alive, thanks.

Last year, I rendered a map with a 1.19 world which worked like a charm.
However, this year I decided to try it again with a 1.20 world. I checked out your "world120" branch on my server and built the images on there.

The (relevant part of the) docker-compose.yml I use:
```
mapcrafter:
    build:
        context: mapcrafter-world120/
    volumes:
        - /home/.../mc/world:/world:ro
        - /home/.../mcmap:/output
        - /home/.../mapcrafter/config:/config
    command: -c /config/render.conf -j 6
```

Here's my (full) config:
```
output_dir = /output
background_color = #000000

[world:world]
input_dir = /world
dimension = overworld
crop_center_x = 0
crop_center_z = 0
crop_radius = 4000

[world:world_full]
input_dir = /world
dimension = overworld

[global:map]
world = world
render_view = isometric
render_mode = daylight
rotations = top-left top-right bottom-right bottom-left

[map:map_world_day]
name = 3D, Tag
```

And everything seems to work fine, except for some blocks. Solid blocks are rendered way too dark.
This is the output as seen on the output website:
![render](https://github.com/miclav/mapcrafter/assets/30687174/ae6703d0-75e6-40e9-8b98-e70c2b302042)

At first I thought the textures weren't loaded correctly, however when I increase the brightness in the dark areas, the textures are suddenly visible.
![render_bright](https://github.com/miclav/mapcrafter/assets/30687174/23056181-03f1-4605-b7c6-ad1d4534d92f)

Thank you!
